### ISSUE TITLE
Hard-coded CLA for app-ethereum (`0xE0`)

### ISSUE THREAD

**Issue by xJonathanLEI** [summa-tx/coins#137]
In the implementation of `APDUCommand`'s `write_to()` method, the first serialized byte (`CLA`) is hard-coded to be `0xE0`, the application identifier for `app-ethereum`:

https://github.com/summa-tx/coins/blob/51c72c14cb1c0d55bb78b292b80846dd1c1d7a2c/crates/ledger/src/common.rs#L104

This has resulted in the `coins-ledger` app not being functional with anything other than the Ethereum Ledger app. It seems to me that this crate contains otherwise nothing Ethereum-specific. So I guess this should be considered a bug.

**Comment by xJonathanLEI** [comment]
The appropriate fix here seems to add a `cla` field to `APDUCommand`. That would be a breaking change though. What do you think? @prestwich

**Comment by prestwich** [comment]
can you provide some citation? I have used this library with bitcoin a number of times

**Comment by xJonathanLEI** [comment]
Yep. So it looks like all the OG apps use `0xE0`, including `app-ethereum` and `app-bitcoin`.

So first for `app-ethereum` you can see [here](https://github.com/LedgerHQ/app-ethereum/blob/76e8690a68fb84910d09fbfd14cc975cefabe41a/src/apdu_constants.h#L9) it's using `CLA` of `0xE0`.

Then for **legacy** `app-bitcoin` [here](https://github.com/LedgerHQ/app-bitcoin/blob/207b65e99b0371b69b3941b30d0fb0c4b83a44d6/doc/btc.asc?plain=1#L45-L63) shows it's also using that. This explains why you've been able to use it with the Bitcoin app as well.

Apparently the **new** Bitcoin app (i.e. `app-bitcoin-new`) uses `0xE1` instead, as shown [here](https://github.com/LedgerHQ/app-bitcoin-new/blob/ec0ca4a1ff6ea496e5d38537af1b3fe50bb4b548/doc/v0/bitcoin.md?plain=1#L11). What this means is that using this library even for the new Bitcoin app wouldn't work.

Then now you have the Starknet app which [uses](https://github.com/LedgerHQ/app-starknet/blob/588c6690f9a3ff1a9d7600ec05124b452e128ffa/src/main.rs#L73) `0x5A`.

Hopefully this shows how CLA should be configurable instead of hard-coded :)
